### ISSUE TITLE
unable to generate report using gradle

### ISSUE THREAD

**Issue by reachkrishnaraj** [d10xa/gradle-allure-plugin#5]
I get the following error. Any solution is appreciated.

My config:
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "ru.d10xa:gradle-allure-plugin:0.5.1"
    }
}

apply plugin: 'ru.d10xa.allure'

allure {
    aspectjweaver = true
    testNG = true

```
allureVersion = "1.4.0"
aspectjVersion = "1.8.0"
```

}

Error:

Caused by: java.lang.NoSuchMethodError: org.codehaus.groovy.runtime.DefaultGroovyMethods.each(Ljava/util/Set;Lgroovy/lang/Closure;)Ljava/util/Set;
    at ru.d10xa.allure.AllurePlugin.applyAspectjweaver(AllurePlugin.groovy:66)
    at ru.d10xa.allure.AllurePlugin.access$2(AllurePlugin.groovy)
    at ru.d10xa.allure.AllurePlugin$_apply_closure1.doCall(AllurePlugin.groovy:26)
    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
    at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
    at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
    ... 43 more

**Comment by d10xa** [comment]
@reachkrishnaraj You need to update gradle version

**Comment by reachkrishnaraj** [comment]
Thanks @d10xa Andrey. I will try that and update this thread.
